#!/bin/sh -e
PKG=arsoft-web-ddns

case "$1" in
    configure|upgrade)
        /usr/lib/$PKG/manage.py syncdb --noinput
        #/usr/lib/$PKG/manage.py collectstatic -l --noinput
        # make sure database is owned by www-data
        chown www-data.www-data -R /var/lib/arsoft/web/ddns
        # an nobody can except www-data can access the database files
        chmod 0750 /var/lib/arsoft/web/ddns
        ;;
esac

#DEBHELPER#

exit 0
